package natureserve

import (
	. "github.com/smartystreets/goconvey/convey"
	"testing"
	"golang.org/x/net/context"
	"fmt"
	"bitbucket.org/heindl/processors/utils"
)

func TestTaxonFetcher(t *testing.T) {

	t.Parallel()

	Convey("should fetch natureserve", t, func() {

		names := []string{
			"cantharellus cascadensis",
			"cantharellus cibarius longipes",
			"merulius alectorolophoides",
			"merulius cantharellus",
			"agaricus alectorolophoides",
			"cantharellus edulis",
			"cantharellus cibarius pallidifolius",
			"cantharellus cibarius salmoneus",
			"cantharellus carneoalbus",
			"agaricus chantarellus",
			"cantharellus cibarius albipes",
			"merulius cibarius",
			"agaricus cantharellus",
			"cantharellus cibarius rufescens",
			"cantharellus cibarius squamulosus",
			"cantharellus pallens",
			"cantharellus alborufescens",
			"cantharellus cibarius neglectus",
			"cantharellus cibarius pallidus",
			"cantharellus cibarius cibarius",
			"cantharellus pallidus",
			"cantharellus cibarius albus",
			"chanterel alectorolophoides",
			"cantharellus neglectus",
			"cantharellus cibarius nanus",
			"cantharellus cibarius alborufescens",
			"cantharellus cibarius squamosus",
			"cantharellus cibarius latifolius",
			"cantharellus cibarius umbrinus",
			"chanterel chantarellus",
			"cantharellus cibarius multiramis",
			"alectorolophoides cibarius",
			"cantharellus cibarius flavipes",
			"chanterel cantharellus",
			"cantharellus cibarius albidus",
			"agaricus chanterellus",
			"craterellus cibarius",
			"cantharellus cibarius",
			"cantharellus vulgaris",
			"cantharellus cibarius rufipes",
			"cantharellus cibarius bicolor",
			"merulius chantarellus",
			"cantharellus rufipes",
			"cantharellus cibarius carneoalbus",
			"cantharellus cibarius inodorus",
			"morchella angusticeps",
			"morchella angusticeps angusticeps",
			"morchella angusticeps ovoideobrunnea",
			"morchella sextelata",
			"cantharellus eucalyptorum",
			"cantharellus ignicolor",
			"craterellus ignicolor",
			"cantharellus persicinus",
			"cantharellus cinnabarinus australiensis",
			"cantharellus cinnabarinus cinnabarinus",
			"chanterel cinnabarinus",
			"hygrophorus cinnabarinus",
			"mastocephalus cinnabarinus",
			"cantharellus cinnabarinus",
			"agaricus cinnabarinus",
			"cantharellus cibarius australiensis",
			"cantharellus doederleini",
			"cycloseris doederleini",
			"fungia doederleini",
			"fungia doderleini",
			"morchella esculenta",
			"morchella umbrina",
			"morchella conica",
			"morchella vulgaris",
			"morchella rotunda fulva",
			"morchella distans longissima",
			"morchella vulgaris tremelloides",
			"morchella esculenta rotunda",
			"morchella conica pygmaea",
			"helvella esculenta",
			"phallus esculentus albus",
			"morchella esculenta rigida",
			"morilla esculenta",
			"morchella rotunda cinerea",
			"morchella conica rigida",
			"morchella esculenta stipitata",
			"morchella vulgaris cinerascens",
			"morchella rotunda rotunda",
			"morchella rotunda",
			"morchella esculenta corrugata",
			"morchella esculenta sterilis",
			"phalloboletus esculentus",
			"morilla conica",
			"morchella rigida",
			"phallus esculentus fuscus",
			"morchella conica elata",
			"morchella conica cylindrica",
			"morchella pubescens",
			"morchella rotunda crassipes",
			"morchella conica nigra",
			"morchella esculenta lutescens",
			"morchella conica conica",
			"morchella esculenta dunensis",
			"morchella esculenta ovalis",
			"morchella umbrina umbrina",
			"morchella rotunda alba",
			"morchella esculenta pubescens",
			"morchella ovalis pallida",
			"morchella esculenta mahoniae",
			"morchella esculenta aurantiaca",
			"morchella conica meandriformis",
			"morchella rotunda pallida",
			"morchella rotunda pubescens",
			"morchella abietina",
			"morchella vulgaris albida",
			"phallus esculentus rotundus",
			"morchella vulgaris alba",
			"morchella esculenta esculenta",
			"morchella esculenta violacea",
			"morchella tremelloides",
			"morchella esculenta umbrinoides",
			"morchella prunarii",
			"morchella conica angusticeps",
			"morchella dunensis sterile",
			"morchella esculenta grisea",
			"morchella conica pusilla",
			"morchella dunensis sterilis",
			"phallus esculentus",
			"morchella cylindrica",
			"morchella conica metheformis",
			"morchella esculenta vulgaris",
			"morchella esculenta albida",
			"phallus esculentus esculentus",
			"morilla tremelloides",
			"morchella conica crassa",
			"morchella esculenta alba",
			"morchella esculenta atrotomentosa",
			"morchella esculenta viridis",
			"morchella dunensis",
			"morchella rotunda esculenta",
			"morchella lutescens",
			"morchella esculenta conica",
			"morchella distans distans",
			"morchella conica flexuosa",
			"morchella esculenta brunnea",
			"morchella vulgaris parvula",
			"morchella vulgaris vulgaris",
			"morellus esculentus",
			"morchella esculenta fulva",
			"morchella esculenta roseostraminea",
			"morchella conica cilicicae",
			"morchella esculenta prunarii",
			"morchella esculenta theobromichroa",
			"morchella esculenta rubroris",
			"morchella esculenta abietina",
			"morchella conica ceracea",
			"morchella rotunda rigida",
			"morchella esculenta umbrina",
			"morchella distans spathulata",
			"morchella umbrina macroalveola",
			"morchella viridis",
			"morchella conica serotina",
			"morchella dunensis dunensis",
			"morchella rotunda minutula",
			"morchella conica distans",
			"morchella conica violeipes",
			"phallus tremelloides",
			"morchella distans",
			"phallus esculentus cinereus",
			"boletus edulis",
			"boletus edulis ochraceus",
			"boletus edulis clavipes",
			"boletus edulis grandedulis",
			"dictyopus edulis edulis",
			"boletus clavipes",
			"boletus edulis edulis",
			"boletus persoonii",
			"boletus edulis citrinus",
			"boletus venturii",
			"boletus slovenicus",
			"boletus edulis quercus",
			"boletus edulis praecox",
			"boletus edulis quercicola",
			"boletus edulis elephantinus",
			"boletus edulis euedulis",
			"dictyopus edulis",
			"suillus citrinus",
			"boletus edulis tuberosus",
			"tubiporus edulis",
			"boletus elephantinus",
			"boletus edulis laevipes",
			"boletus edulis pseudopurpureus",
			"tubiporus edulis euedulis",
			"boletus edulis olivaceobrunneus",
			"boletus solidus",
			"boletus edulis albus",
			"boletus edulis trisporus",
			"boletus quercicola",
			"boletus edulis slovenicus",
			"boletus edulis arenarius",
			"tubiporus edulis edulis",
			"boletus edulis betulicola",
			"boletus citrinus",
			"boletus edulis arcticus",
			"boletus edulis tardus",
			"tylopilus porphyrosporus olivaceobrunneus",
			"leccinum elephantinum",
			"boletus edulis communis",
			"boletus olivaceobrunneus",
			"boletus reticulatus albus",
			"boletus edulis subaereus",
			"boletus betulicola",
			"boletus edulis roseipes",
			"boletus reticulatus citrinus",
			"boletus edulis piceicola",
			"boletus edulis abietis",
			"leccinum edule",
			"morchella americana",
			"morchella frustrata",
			"morchella importuna",
			"morchella snyderi",
			"morchella tridentina",
			"morchella diminutiva",
			"morchella brunnea",
			"morchella esculentoides",
			"morchella conica pseudoeximia",
			"morchella quercus-ilicis quercus-ilicis",
			"morchella americana americana",
			"morchella elatoides elatoides",
			"morchella americana elongata",
			"morchella elatoides",
			"morchella quercus-ilicis",
			"morchella elatoides elegans",
			"cantharellus goossensiae",
			"hygrophorus goossensiae",
			"morchella guatemalensis",
			"cantharellus amethysteus",
			"cantharellus amethysteus amethysteus",
			"cantharellus amethysteus substypticus",
			"cantharellus cibarius amethysteus",
			"craterellus amethysteus",
			"merulius amethysteus",
			"cantharellus elsae",
			"hygrophorus elsae",
			"cantharellus solidus",
			"cantharellus insignis",
			"craterellus insignis",
			"cantharellus defibulatus",
			"cantharellus cibarius defibulatus",
			"cantharellus tabernensis",
			"morchella crassipes",
			"morchella esculenta crassipes",
			"morchella crispa",
			"phallus crassipes",
			"morchella crassipes crispa",
			"mitrophora hybrida crassipes",
			"morchella crassipes crassipes",
			"phalloboletus crassipes",
			"morchella australiana",
			"cantharellus phasmatis",
			"cantharellus spectaculus",
			"morchella rufobrunnea",
			"cantharellus wellingtonensis",
			"cantharellus subcibarius",
			"cantharellus subcibarius rugosivenis",
			"cantharellus subcibarius sordidus",
			"cantharellus subcibarius subcibarius",
			"morchella punctipes",
			"cantharellus velutinus",
			"cantharellus chicagoensis",
			"cantharellus appalachiensis",
			"cantharellus flavus",
			"cantharellus tricolor",
			"cantharellus concinnus",
			"cantharellus nigrescens",
			"morchella populiphila",
			"cantharellus friesii",
			"merulius friesii",
			"cantharellus variabilis",
			"cantharellus atrolilacinus",
			"cantharellus attenuatus",
			"morchella deliciosa deliciosa",
			"morchella deliciosa elegans",
			"morchella deliciosa incarnata",
			"morchella deliciosa",
			"morchella deliciosa purpurascens",
			"morilla deliciosa",
			"morilla deliciosa deliciosa",
			"morchella conica deliciosa",
			"morchella pragensis",
			"morchella pragensis mirabilis",
			"morchella pragensis pragensis",
			"morchella pragensis pterigoides",
			"morchella pragensis turriformis",
			"morchella pterigoides",
			"cantharellus texensis",
			"cantharellus californicus",
			"cantharellus congolensis",
			"morchella septimelata",
			"morchella prava",
			"cantharellus lateritius",
			"trombetta lateritia",
			"cantharellus lateritius colombianus",
			"cantharellus lateritius lateritius",
			"craterellus lateritius",
			"cantharellus subpruinosus",
			"cantharellus odoratus odoratus",
			"craterellus cantharellus albus",
			"merulius odoratus",
			"cantharellus odoratus albus",
			"craterellus odoratus solidostipite",
			"craterellus odoratus odoratus",
			"cantharellus odoratus",
			"craterellus odoratus",
			"trombetta odorata",
			"morchella eximia",
			"morchella costata",
			"morchella elata costata",
			"morchella costata acuminata",
			"morchella costata costata",
			"morchella costata teratologique",
			"morchella eximia acuminata",
			"morchella conica acuminata",
			"phallus costatus",
			"morchella eximia schizocostata",
			"morchella eximia eximia",
			"cantharellus guineensis",
			"cantharellus cinereus",
			"merulius hydropipes",
			"pseudocraterellus cinereus",
			"craterellus cinereus",
			"morchella elata",
			"morchella conica purpurascens",
			"morchella elata purpurascens",
			"boletus esculentus pinguis",
			"suillus pinguis",
			"morchella elata nigripes",
			"morchella purpurascens purpurascens",
			"morchella purpurascens",
			"boletus esculentus esculentus",
			"morchella conica nigripes",
			"morchella elata clusii",
			"morchella elata elata",
			"morchella purpurascens heteroparaphysa",
			"boletus esculentus fuligineus",
			"morchella elata nivea",
			"morchella purpurascens ionoviridis",
			"boletus esculentus",
			"cantharellus lutescens luteocomus",
			"helvella tubaeformis",
			"craterellus lutescens citrinosulphureus",
			"helvella tubaeformis fulva",
			"craterellus lutescens lutescens",
			"merulius tubaeformis",
			"cantharellus lutescens lutescens",
			"agaricus aurora",
			"cantharellus lutescens schizocroicus",
			"craterellus lutescens albidus",
			"cantharellus tubaeformis",
			"craterellus lutescens",
			"cantharellus lutescens niveipes",
			"craterellus lutescens crocatus",
			"cantharellus infundibuliformis tubiformis",
			"cantharellus tubaeformis lutescens",
			"craterellus lutescens luteocomus",
			"cantharellus lutescens",
			"cantharellus lutescens albidus",
			"cantharellus lutescens bisporus",
			"cantharellus luteocomus",
			"craterellus lutescens bisporus",
			"helvella tubaeformis tubaeformis",
			"elvela tubaeformis",
			"helvella tubaeformis lutea",
			"cantharellus lutescens axanthus",
			"craterellus lutescens niveipes",
			"cantharellus aurora",
			"cantharellus roseocanus",
			"cantharellus cibarius roseocanus",
			"cantharellus camphoratus",
			"cantharellus variabilicolor",
			"cantharellus ferruginascens",
			"cantharellus cibarius ferruginascens",
			"cantharellus ferruginascens ferruginascens",
			"cantharellus jebbi",
			"cantharellus minor",
			"cantharellus minor intensissimus",
			"cantharellus minor minor",
			"merulius minor",
			"cantharellus formosus",
			"cantharellus subalbidus",
			"cantharellus lewisii",
			"cantharellus subincarnatus",
			"lentinus incarnatus",
			"cantharellus incarnatus",
			"cantharellus subincarnatus rubrosalmoneus",
			"cantharellus subincarnatus subincarnatus",
			"cantharellus noumeae",
			"morchella tomentosa",
			"cantharellus ianthinoxanthus",
			"cantharellus cibarius janthinoxanthus",
			"craterellus ianthinoxanthus",
			"cantharellus cibarius ianthinoxanthus",
			"cantharellus concinnius",
			"incertae sedis",
			"cantharellus guyanensis",
			"merulius guyanensis",
		}

		usages, err := FetchNameUsages(context.Background(), names, nil)
		So(err, ShouldBeNil)
		fmt.Println(utils.JsonOrSpew(usages))
	})

	//SkipConvey("should fetch inaturalist schemes", t, func() {
	//	f := fetcher{}
	//	srcs, err := f.fetchDataSources(store.INaturalistTaxonID("58583"), store.CanonicalName("Limenitis arthemis ssp. arthemis"), true)
	//	So(err, ShouldBeNil)
	//	So(len(srcs), ShouldEqual, 3)
	//	So(srcs[0].SourceID, ShouldEqual, store.SourceType("11"))
	//	So(srcs[0].Kind, ShouldEqual, store.DataSourceKindDescription)
	//	So(srcs[1].SourceID, ShouldEqual, store.SourceType("27"))
	//	So(srcs[1].Kind, ShouldEqual, store.DataSourceKindOccurrence)
	//	So(srcs[2].SourceID, ShouldEqual, store.SourceType("27"))
	//	So(srcs[2].Kind, ShouldEqual, store.DataSourceKindPhoto)
	//})
	//
	//Convey("should fetch additional taxon ids from the gbif based on the canonical name", t, func() {
	//	f := fetcher{}
	//	ids, err := f.fetchAdditionalGBIFTaxonIDs("Morchella esculenta", store.TargetID("2594602"))
	//	So(err, ShouldBeNil)
	//	So(ids[0], ShouldEqual, store.INaturalistTaxonID("8574619"))
	//
	//	ids, err = f.fetchAdditionalGBIFTaxonIDs("Cantharellus cibarius", store.TargetID("5249504"))
	//	So(err, ShouldBeNil)
	//	Println(ids)
	//})
	//
	//Convey("should fetch all species in subfamily Limenitidinae", t, func() {
	//
	//	f := fetcher{
	//		Store: store.NewTestTaxaStore(),
	//		Clock: clockwork.NewFakeClock(),
	//	}
	//
	//	cxt := context.Background()
	//
	//	taxa, err := f.Store.ReadTaxa(cxt)
	//	So(err, ShouldBeNil)
	//	So(len(taxa), ShouldEqual, 0)
	//
	//	So(f.FetchProcessTaxa(cxt, []store.INaturalistTaxonID{store.INaturalistTaxonID("58583")}), ShouldBeNil)
	//
	//	taxa, err = f.Store.ReadTaxa(cxt)
	//	So(err, ShouldBeNil)
	//	So(len(taxa), ShouldEqual, 19)
	//
	//	taxa, err = f.Store.ReadSpecies(cxt)
	//	So(err, ShouldBeNil)
	//	So(len(taxa), ShouldEqual, 7)
	//
	//	dataSources, err := f.Store.GetOccurrenceDataSources(cxt, store.INaturalistTaxonID(""))
	//	So(err, ShouldBeNil)
	//	So(len(dataSources), ShouldEqual, 6)
	//	have := []string{}
	//	for i := range dataSources {
	//		have = append(have, string(dataSources[i].TaxonID))
	//	}
	//
	//	dataSources, err = f.Store.GetOccurrenceDataSources(cxt, taxa[0].ID)
	//	So(err, ShouldBeNil)
	//	So(len(dataSources), ShouldEqual, 1)
	//
	//	dataSources, err = f.Store.GetOccurrenceDataSources(cxt, taxa[2].ID)
	//	So(err, ShouldBeNil)
	//	So(len(dataSources), ShouldEqual, 1)
	//
	//	dataSources, err = f.Store.GetOccurrenceDataSources(cxt, taxa[3].ID)
	//	So(err, ShouldBeNil)
	//	So(len(dataSources), ShouldEqual, 1)
	//
	//	Reset(func() {
	//		So(f.Store.Close(), ShouldBeNil)
	//	})
}
