package ecoregions


// Order

type Biome int

var BiomeDefinitions = map[Biome]string{
	Biome(1):  "Tropical & Subtropical Moist Broadleaf Forests",
	Biome(2):  "Tropical & Subtropical Dry Broadleaf Forests",
	Biome(3):  "Tropical & Subtropical Coniferous Forests",
	Biome(4):  "Temperate Broadleaf & Mixed Forests",
	Biome(5):  "Temperate Conifer Forests",
	Biome(6):  "Boreal Forests/Taiga",
	Biome(7):  "Tropical & Subtropical Grasslands, Savannas & Shrublands",
	Biome(8):  "Temperate Grasslands, Savannas & Shrublands",
	Biome(9):  "Flooded Grasslands & Savannas",
	Biome(10): "Montane Grasslands & Shrublands",
	Biome(11): "Tundra",
	Biome(12): "Mediterranean Forests, Woodlands & Scrub",
	Biome(13): "Deserts & Xeric Shrublands",
	Biome(14): "Mangroves",
}


type Realm string //  Biogeographical Realm
var RealmDefinitions = map[Realm]string{
	Realm("AA"): "Australasia",
	Realm("AN"): "Antarctic",
	Realm("AT"): "Afrotropics",
	Realm("IM"): "IndoMalay",
	Realm("NA"): "Nearctic",
	Realm("NT"): "Neotropics",
	Realm("OC"): "Oceania",
	Realm("PA"): "Palearctic",
}

type GlobalStatus int
// A 30-year prediction of future conservation status given current conservation status and trajectories.
var GlobalStatusDefinitions = map[GlobalStatus]string{
	GlobalStatus(1): "CRITICAL OR ENDANGERED",
	GlobalStatus(2): "VULNERABLE",
	GlobalStatus(3): "RELATIVELY STABLE OR INTACT",
}

type EcoID int
var EcoIDDefinitions = map[EcoID]string{
	EcoID(60122): "Eastern Panamanian montane forests",
	EcoID(60106): "Caatinga Enclaves moist forests",
	EcoID(61311): "Malpelo Island xeric scrub",
	EcoID(60909): "Southern Cone Mesopotamian savanna",
	EcoID(61006): "Northern Andean páramo",
	EcoID(60215): "Hispaniolan dry forests",
	EcoID(60402): "Magellanic subpolar forests",
	EcoID(61303): "Atacama desert",
	EcoID(60165): "Southern Andean Yungas",
	EcoID(61001): "Central Andean dry puna",
	EcoID(60163): "Solimões-Japurá moist forests",
	EcoID(61402): "Bahamian-Antillean mangroves",
	EcoID(60309): "Sierra Madre del Sur pine-oak forests",
	EcoID(60123): "Fernando de Noronha-Atol das Rocas moist forests",
	EcoID(61307): "Galápagos Islands scrubland mosaic",
	EcoID(60147): "Orinoco Delta swamp forests",
	EcoID(60224): "Panamanian dry forests",
	EcoID(60118): "Cordillera Oriental montane forests",
	EcoID(60142): "Napo moist forests",
	EcoID(60213): "Cuban dry forests",
	EcoID(60120): "Cuban moist forests",
	EcoID(60707): "Guianan savanna",
	EcoID(60302): "Belizian pine forests",
	EcoID(60206): "Bolivian montane dry forests",
	EcoID(60157): "Purus-Madeira moist forests",
	EcoID(60160): "Serra do Mar coastal forests",
	EcoID(60803): "Humid Pampas",
	EcoID(60705): "Clipperton Island shrub and grasslands",
	EcoID(61306): "Cuban cactus scrub",
	EcoID(61405): "South American Pacific mangroves",
	EcoID(60161): "Sierra de los Tuxtlas",
	EcoID(61008): "Southern Andean steppe",
	EcoID(60212): "Chiquitano dry forests",
	EcoID(60128): "Iquitos varzeá",
	EcoID(60204): "Bajío dry forests",
	EcoID(60145): "Northwestern Andean montane forests",
	EcoID(60117): "Cordillera La Costa montane forests",
	EcoID(60114): "Chimalapas montane forests",
	EcoID(60141): "Monte Alegre varzeá",
	EcoID(60126): "Gurupa varzeá",
	EcoID(60169): "Pantepui",
	EcoID(61308): "Guajira-Barranquilla xeric scrub",
	EcoID(60201): "Apure-Villavicencio dry forests",
	EcoID(61406): "Southern Atlantic mangroves",
	EcoID(60121): "Eastern Cordillera real montane forests",
	EcoID(60133): "Juruá-Purus moist forests",
	EcoID(60182): "Guianan piedmont and lowland moist forests",
	EcoID(60174): "Ucayali moist forests",
	EcoID(60136): "Magdalena Valley montane forests",
	EcoID(61403): "Mesoamerican Gulf-Caribbean mangroves",
	EcoID(60205): "Balsas dry forests",
	EcoID(60304): "Cuban pine forests",
	EcoID(60801): "Espinal",
	EcoID(60105): "Bolivian Yungas",
	EcoID(60156): "Purus varzeá",
	EcoID(60108): "Catatumbo moist forests",
	EcoID(60177): "Veracruz montane forests",
	EcoID(60139): "Maranhão Babaçu forests",
	EcoID(60168): "Tapajós-Xingu moist forests",
	EcoID(60124): "Guianan Highlands moist forests",
	EcoID(60159): "Santa Marta montane forests",
	EcoID(60303): "Central American pine-oak forests",
	EcoID(60173): "Uatuma-Trombetas moist forests",
	EcoID(61316): "Tehuacán Valley matorral",
	EcoID(60153): "Peruvian Yungas",
	EcoID(60112): "Central American montane forests",
	EcoID(60306): "Miskito pine forests",
	EcoID(60167): "Talamancan montane forests",
	EcoID(60404): "Valdivian temperate forests",
	EcoID(60211): "Chiapas Depression dry forests",
	EcoID(61304): "Caatinga",
	EcoID(60137): "Magdalena-Urabá moist forests",
	EcoID(61318): "St. Peter and St. Paul rocks",
	EcoID(60301): "Bahamian pine mosaic",
	EcoID(61301): "Araya and Paria xeric scrub",
	EcoID(61401): "Amazon-Orinoco-Southern Caribbean mangroves",
	EcoID(60305): "Hispaniolan pine forests",
	EcoID(60230): "Southern Pacific dry forests",
	EcoID(60135): "Madeira-Tapajós moist forests",
	EcoID(60223): "Marañón dry forests",
	EcoID(60210): "Dry Chaco",
	EcoID(60181): "Yucatán moist forests",
	EcoID(60129): "Isthmian-Atlantic moist forests",
	EcoID(60907): "Pantanal",
	EcoID(61010): "High Monte",
	EcoID(60710): "Uruguayan savanna",
	EcoID(61003): "Central Andean wet puna",
	EcoID(61007): "Santa Marta páramo",
	EcoID(60146): "Oaxacan montane forests",
	EcoID(60127): "Hispaniolan moist forests",
	EcoID(60109): "Cauca Valley montane forests",
	EcoID(60908): "Paraná flooded savanna",
	EcoID(60802): "Low Monte",
	EcoID(60401): "Juan Fernández Islands temperate forests",
	EcoID(60158): "Rio Negro campinarana",
	EcoID(60110): "Cayos Miskitos-San Andrés and Providencia moist forests",
	EcoID(60103): "Bahia coastal forests",
	EcoID(61314): "San Lucan xeric scrub",
	EcoID(60906): "Orinoco wetlands",
	EcoID(60708): "Humid Chaco",
	EcoID(60152): "Pernambuco interior forests",
	EcoID(61002): "Central Andean puna",
	EcoID(60310): "Trans-Mexican Volcanic Belt pine-oak forests",
	EcoID(60903): "Enriquillo wetlands",
	EcoID(60131): "Jamaican moist forests",
	EcoID(61312): "Motagua Valley thornscrub",
	EcoID(60905): "Guayaquil flooded grasslands",
	EcoID(60134): "Leeward Islands moist forests",
	EcoID(61305): "Caribbean shrublands",
	EcoID(60148): "Pantanos de Centla",
	EcoID(60144): "Northeastern Brazil restingas",
	EcoID(60403): "San Félix-San Ambrosio Islands temperate forests",
	EcoID(60225): "Patía Valley dry forests",
	EcoID(60119): "Costa Rican seasonal moist forests",
	EcoID(60107): "Caqueta moist forests",
	EcoID(60150): "Alto Paraná Atlantic forests",
	EcoID(60111): "Central American Atlantic moist forests",
	EcoID(60702): "Beni savanna",
	EcoID(60176): "Veracruz moist forests",
	EcoID(60227): "Sierra de la Laguna dry forests",
	EcoID(60113): "Chiapas montane forests",
	EcoID(60151): "Pernambuco coastal forests",
	EcoID(61309): "La Costa xeric shrublands",
	EcoID(60220): "Lesser Antillean dry forests",
	EcoID(60235): "Yucatán dry forests",
	EcoID(60233): "Veracruz dry forests",
	EcoID(60143): "Negro-Branco moist forests",
	EcoID(60207): "Cauca Valley dry forests",
	EcoID(60172): "Trindade-Martin Vaz Islands tropical forests",
	EcoID(60164): "South Florida rocklands",
	EcoID(60226): "Puerto Rican dry forests",
	EcoID(60104): "Bahia interior forests",
	EcoID(60132): "Japurá-Solimoes-Negro moist forests",
	EcoID(60180): "Xingu-Tocantins-Araguaia moist forests",
	EcoID(60140): "Mato Grosso seasonal forests",
	EcoID(60221): "Magdalena Valley dry forests",
	EcoID(60154): "Petén-Veracruz moist forests",
	EcoID(60179): "Windward Islands moist forests",
	EcoID(60709): "Llanos",
	EcoID(60704): "Cerrado",
	EcoID(60170): "Tocantins/Pindare moist forests",
	EcoID(61404): "Northern Mesoamerican Pacific mangroves",
	EcoID(60228): "Sinaloan dry forests",
	EcoID(61407): "Southern Mesoamerican Pacific mangroves",
	EcoID(60178): "Western Ecuador moist forests",
	EcoID(60125): "Guianan moist forests",
	EcoID(60138): "Marajó varzeá",
	EcoID(60102): "Atlantic Coast restingas",
	EcoID(60703): "Campos Rupestres montane savanna",
	EcoID(60214): "Ecuadorian dry forests",
	EcoID(60904): "Everglades",
	EcoID(60216): "Islas Revillagigedo dry forests",
	EcoID(60217): "Jalisco dry forests",
	EcoID(60101): "Araucaria moist forests",
	EcoID(60115): "Chocó-Darién moist forests",
	EcoID(60162): "Sierra Madre de Chiapas moist forests",
	EcoID(60149): "Guianan freshwater swamp forests",
	EcoID(60232): "Tumbes-Piura dry forests",
	EcoID(60222): "Maracaibo dry forests",
	EcoID(61201): "Chilean matorral",
	EcoID(60229): "Sinú Valley dry forests",
	EcoID(61315): "Sechura desert",
	EcoID(60219): "Lara-Falcón dry forests",
	EcoID(60307): "Sierra de la Laguna pine-oak forests",
	EcoID(60175): "Venezuelan Andes montane forests",
	EcoID(60218): "Jamaican dry forests",
	EcoID(60805): "Patagonian steppe",
	EcoID(61005): "Cordillera de Merida páramo",
	EcoID(60130): "Isthmian-Pacific moist forests",
	EcoID(61004): "Cordillera Central páramo",
	EcoID(60171): "Trinidad and Tobago moist forests",
	EcoID(60308): "Sierra Madre de Oaxaca pine-oak forests",
	EcoID(60155): "Puerto Rican moist forests",
	EcoID(60116): "Cocos Island moist forests",
	EcoID(61313): "Paraguana xeric scrub",
	EcoID(60202): "Atlantic dry forests",
	EcoID(60902): "Cuban wetlands",
	EcoID(60209): "Central American dry forests",
	EcoID(60166): "Southwest Amazon moist forests",
}

type EcoCode string
var EcoCodeDefinitions = map[EcoCode]string{
	EcoCode("NT0134"): "Leeward Islands moist forests",
	EcoCode("NT0174"): "Ucayali moist forests",
	EcoCode("NT0162"): "Sierra Madre de Chiapas moist forests",
	EcoCode("NT0222"): "Maracaibo dry forests",
	EcoCode("NT0909"): "Southern Cone Mesopotamian savanna",
	EcoCode("NT0310"): "Trans-Mexican Volcanic Belt pine-oak forests",
	EcoCode("NT1312"): "Motagua Valley thornscrub",
	EcoCode("NT1318"): "St. Peter and St. Paul rocks",
	EcoCode("NT0235"): "Yucatán dry forests",
	EcoCode("NT0117"): "Cordillera La Costa montane forests",
	EcoCode("NT0214"): "Ecuadorian dry forests",
	EcoCode("NT1304"): "Caatinga",
	EcoCode("NT0707"): "Guianan savanna",
	EcoCode("NT1306"): "Cuban cactus scrub",
	EcoCode("NT0903"): "Enriquillo wetlands",
	EcoCode("NT0218"): "Jamaican dry forests",
	EcoCode("NT1005"): "Cordillera de Merida páramo",
	EcoCode("NT0161"): "Sierra de los Tuxtlas",
	EcoCode("NT0145"): "Northwestern Andean montane forests",
	EcoCode("NT0801"): "Espinal",
	EcoCode("NT1301"): "Araya and Paria xeric scrub",
	EcoCode("NT0180"): "Xingu-Tocantins-Araguaia moist forests",
	EcoCode("NT0108"): "Catatumbo moist forests",
	EcoCode("NT0219"): "Lara-Falcón dry forests",
	EcoCode("NT0157"): "Purus-Madeira moist forests",
	EcoCode("NT1311"): "Malpelo Island xeric scrub",
	EcoCode("NT0110"): "Cayos Miskitos-San Andrés and Providencia moist forests",
	EcoCode("NT1403"): "Mesoamerican Gulf-Caribbean mangroves",
	EcoCode("NT0227"): "Sierra de la Laguna dry forests",
	EcoCode("NT0167"): "Talamancan montane forests",
	EcoCode("NT1307"): "Galápagos Islands scrubland mosaic",
	EcoCode("NT0703"): "Campos Rupestres montane savanna",
	EcoCode("NT0124"): "Guianan Highlands moist forests",
	EcoCode("NT0155"): "Puerto Rican moist forests",
	EcoCode("NT0135"): "Madeira-Tapajós moist forests",
	EcoCode("NT1314"): "San Lucan xeric scrub",
	EcoCode("NT0153"): "Peruvian Yungas",
	EcoCode("NT0172"): "Trindade-Martin Vaz Islands tropical forests",
	EcoCode("NT0201"): "Apure-Villavicencio dry forests",
	EcoCode("NT0182"): "Guianan piedmont and lowland moist forests",
	EcoCode("NT0150"): "Alto Paraná Atlantic forests",
	EcoCode("NT0120"): "Cuban moist forests",
	EcoCode("NT0119"): "Costa Rican seasonal moist forests",
	EcoCode("NT0232"): "Tumbes-Piura dry forests",
	EcoCode("NT0169"): "Pantepui",
	EcoCode("NT0128"): "Iquitos varzeá",
	EcoCode("NT1405"): "South American Pacific mangroves",
	EcoCode("NT0107"): "Caqueta moist forests",
	EcoCode("NT0121"): "Eastern Cordillera real montane forests",
	EcoCode("NT0144"): "Northeastern Brazil restingas",
	EcoCode("NT0168"): "Tapajós-Xingu moist forests",
	EcoCode("NT0401"): "Juan Fernández Islands temperate forests",
	EcoCode("NT0220"): "Lesser Antillean dry forests",
	EcoCode("NT0215"): "Hispaniolan dry forests",
	EcoCode("NT0306"): "Miskito pine forests",
	EcoCode("NT0307"): "Sierra de la Laguna pine-oak forests",
	EcoCode("NT0205"): "Balsas dry forests",
	EcoCode("NT0217"): "Jalisco dry forests",
	EcoCode("NT0123"): "Fernando de Noronha-Atol das Rocas moist forests",
	EcoCode("NT0106"): "Caatinga Enclaves moist forests",
	EcoCode("NT1006"): "Northern Andean páramo",
	EcoCode("NT0142"): "Napo moist forests",
	EcoCode("NT0176"): "Veracruz moist forests",
	EcoCode("NT0131"): "Jamaican moist forests",
	EcoCode("NT0115"): "Chocó-Darién moist forests",
	EcoCode("NT0177"): "Veracruz montane forests",
	EcoCode("NT0112"): "Central American montane forests",
	EcoCode("NT0906"): "Orinoco wetlands",
	EcoCode("NT0126"): "Gurupa varzeá",
	EcoCode("NT0221"): "Magdalena Valley dry forests",
	EcoCode("NT1201"): "Chilean matorral",
	EcoCode("NT0216"): "Islas Revillagigedo dry forests",
	EcoCode("NT0164"): "South Florida rocklands",
	EcoCode("NT1407"): "Southern Mesoamerican Pacific mangroves",
	EcoCode("NT0308"): "Sierra Madre de Oaxaca pine-oak forests",
	EcoCode("NT0148"): "Pantanos de Centla",
	EcoCode("NT0304"): "Cuban pine forests",
	EcoCode("NT0907"): "Pantanal",
	EcoCode("NT0204"): "Bajío dry forests",
	EcoCode("NT0904"): "Everglades",
	EcoCode("NT1007"): "Santa Marta páramo",
	EcoCode("NT0171"): "Trinidad and Tobago moist forests",
	EcoCode("NT0158"): "Rio Negro campinarana",
	EcoCode("NT0129"): "Isthmian-Atlantic moist forests",
	EcoCode("NT1008"): "Southern Andean steppe",
	EcoCode("NT0708"): "Humid Chaco",
	EcoCode("NT1404"): "Northern Mesoamerican Pacific mangroves",
	EcoCode("NT1303"): "Atacama desert",
	EcoCode("NT0302"): "Belizian pine forests",
	EcoCode("NT0207"): "Cauca Valley dry forests",
	EcoCode("NT0802"): "Low Monte",
	EcoCode("NT0211"): "Chiapas Depression dry forests",
	EcoCode("NT0206"): "Bolivian montane dry forests",
	EcoCode("NT0147"): "Orinoco Delta swamp forests",
	EcoCode("NT0151"): "Pernambuco coastal forests",
	EcoCode("NT0212"): "Chiquitano dry forests",
	EcoCode("NT1001"): "Central Andean dry puna",
	EcoCode("NT0226"): "Puerto Rican dry forests",
	EcoCode("NT0149"): "Guianan freshwater swamp forests",
	EcoCode("NT0230"): "Southern Pacific dry forests",
	EcoCode("NT1010"): "High Monte",
	EcoCode("NT0101"): "Araucaria moist forests",
	EcoCode("NT0301"): "Bahamian pine mosaic",
	EcoCode("NT1004"): "Cordillera Central páramo",
	EcoCode("NT1313"): "Paraguana xeric scrub",
	EcoCode("NT0710"): "Uruguayan savanna",
	EcoCode("NT1316"): "Tehuacán Valley matorral",
	EcoCode("NT0210"): "Dry Chaco",
	EcoCode("NT0175"): "Venezuelan Andes montane forests",
	EcoCode("NT0305"): "Hispaniolan pine forests",
	EcoCode("NT0105"): "Bolivian Yungas",
	EcoCode("NT0229"): "Sinú Valley dry forests",
	EcoCode("NT0402"): "Magellanic subpolar forests",
	EcoCode("NT0166"): "Southwest Amazon moist forests",
	EcoCode("NT0170"): "Tocantins/Pindare moist forests",
	EcoCode("NT0178"): "Western Ecuador moist forests",
	EcoCode("NT0160"): "Serra do Mar coastal forests",
	EcoCode("NT0132"): "Japurá-Solimoes-Negro moist forests",
	EcoCode("NT0309"): "Sierra Madre del Sur pine-oak forests",
	EcoCode("NT0709"): "Llanos",
	EcoCode("NT0109"): "Cauca Valley montane forests",
	EcoCode("NT0104"): "Bahia interior forests",
	EcoCode("NT0116"): "Cocos Island moist forests",
	EcoCode("NT1315"): "Sechura desert",
	EcoCode("NT0139"): "Maranhão Babaçu forests",
	EcoCode("NT1002"): "Central Andean puna",
	EcoCode("NT1309"): "La Costa xeric shrublands",
	EcoCode("NT1308"): "Guajira-Barranquilla xeric scrub",
	EcoCode("NT0152"): "Pernambuco interior forests",
	EcoCode("NT0202"): "Atlantic dry forests",
	EcoCode("NT0225"): "Patía Valley dry forests",
	EcoCode("NT0156"): "Purus varzeá",
	EcoCode("NT0702"): "Beni savanna",
	EcoCode("NT0143"): "Negro-Branco moist forests",
	EcoCode("NT0103"): "Bahia coastal forests",
	EcoCode("NT0704"): "Cerrado",
	EcoCode("NT0127"): "Hispaniolan moist forests",
	EcoCode("NT0181"): "Yucatán moist forests",
	EcoCode("NT0805"): "Patagonian steppe",
	EcoCode("NT0233"): "Veracruz dry forests",
	EcoCode("NT0118"): "Cordillera Oriental montane forests",
	EcoCode("NT0908"): "Paraná flooded savanna",
	EcoCode("NT0163"): "Solimões-Japurá moist forests",
	EcoCode("NT0146"): "Oaxacan montane forests",
	EcoCode("NT0705"): "Clipperton Island shrub and grasslands",
	EcoCode("NT0179"): "Windward Islands moist forests",
	EcoCode("NT0404"): "Valdivian temperate forests",
	EcoCode("NT1305"): "Caribbean shrublands",
	EcoCode("NT0159"): "Santa Marta montane forests",
	EcoCode("NT0209"): "Central American dry forests",
	EcoCode("NT0111"): "Central American Atlantic moist forests",
	EcoCode("NT0125"): "Guianan moist forests",
	EcoCode("NT0228"): "Sinaloan dry forests",
	EcoCode("NT0136"): "Magdalena Valley montane forests",
	EcoCode("NT0122"): "Eastern Panamanian montane forests",
	EcoCode("NT0137"): "Magdalena-Urabá moist forests",
	EcoCode("NT0223"): "Marañón dry forests",
	EcoCode("NT0403"): "San Félix-San Ambrosio Islands temperate forests",
	EcoCode("NT0114"): "Chimalapas montane forests",
	EcoCode("NT0113"): "Chiapas montane forests",
	EcoCode("NT0303"): "Central American pine-oak forests",
	EcoCode("NT0138"): "Marajó varzeá",
	EcoCode("NT0224"): "Panamanian dry forests",
	EcoCode("NT0803"): "Humid Pampas",
	EcoCode("NT1402"): "Bahamian-Antillean mangroves",
	EcoCode("NT1401"): "Amazon-Orinoco-Southern Caribbean mangroves",
	EcoCode("NT0154"): "Petén-Veracruz moist forests",
	EcoCode("NT0133"): "Juruá-Purus moist forests",
	EcoCode("NT0130"): "Isthmian-Pacific moist forests",
	EcoCode("NT0165"): "Southern Andean Yungas",
	EcoCode("NT1003"): "Central Andean wet puna",
	EcoCode("NT0905"): "Guayaquil flooded grasslands",
	EcoCode("NT0902"): "Cuban wetlands",
	EcoCode("NT0173"): "Uatuma-Trombetas moist forests",
	EcoCode("NT0102"): "Atlantic Coast restingas",
	EcoCode("NT1406"): "Southern Atlantic mangroves",
	EcoCode("NT0141"): "Monte Alegre varzeá",
	EcoCode("NT0140"): "Mato Grosso seasonal forests",
	EcoCode("NT0213"): "Cuban dry forests",
}
