apiVersion: batch/v1
kind: Job
metadata:
  name: species-fetcher
  namespace: phenograph
spec:
  template:
    spec:
      containers:
      - name: species-fetcher
        image: us.gcr.io/phenograph-154419/species-fetcher
        command: ["/main", "--name={{SPECIES_NAME}}"]
        env:
        - name: PHENOGRAPH_MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo
              key: user
        - name: PHENOGRAPH_DARKSKY_SECRET
          valueFrom:
            secretKeyRef:
              name: darksky
              key: token
        - name: PHENOGRAPH_MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo
              key: password
        - name: PHENOGRAPH_MONGO_ADDRESSES
          value: phenograph-mongo-mongodb-replicaset:27017
        - name: PHENOGRAPH_MONGO_RS_NAME
          value: rs0
      restartPolicy: Never