apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: species-fetcher
  namespace: phenograph
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: species-fetcher
    spec:
      containers:
      - name: species-fetcher
        image: us.gcr.io/phenograph-154419/species-fetcher
        env:
        - name: PHENOGRAPH_MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo
              key: user
        - name: PHENOGRAPH_MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo
              key: password
        - name: PHENOGRAPH_MONGO_ADDRESSES
          value: phenograph-mongodb-repli:27017
        - name: PHENOGRAPH_MONGO_RS_NAME
          value: rs0
      - name: nsqd
        image: nsqio/nsq
        command:
        - /nsqd
        - -broadcast-address=species-fetcher
        - -lookupd-tcp-address=nsqlookup-1:4160
        - -lookupd-tcp-address=nsqlookup-2:4160
        - -lookupd-tcp-address=nsqlookup-3:4160
        ports:
        - containerPort: 4150
          name: tcp
          protocol: TCP
        - containerPort: 4151
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - name: data
        emptyDir: {}