package utils

const (
	LogkeyQuery                = "query"
	LogkeyUpdate               = "update"
	LogkeyError                = "error"
	LogkeyCanonicalName        = "canonicalName"
	LogkeyRank                 = "rank"
	LogkeyCount                = "count"
	LogkeyIdentifier           = "identifier"
	LogkeyOccurrence           = "occurrence"
	LogkeyScheme               = "scheme"
	LogkeySource               = "source"
	LogkeyTime                 = "time"
	LogkeyTimes                = "times" // array
	LogkeyDeferError           = "deferError"
	LogkeyURL                  = "url"
	LogkeyTopic                = "topic"
	LogkeyFilePath             = "filepath"
	LogkeyWaypoint             = "waypoint"
	LogkeyWeatherRecord        = "weatherRecord"
	LogkeyMissingWeatherRecord = "missingWeatherRecord"
	LogkeyHost                 = "host"
	LogkeyStatus               = "status"
	LogkeyStatusCode           = "statusCode"
	LogkeyStringValue          = "stringValue"
	LogkeyLatitude             = "latitude"
	LogkeyLongitude            = "longitude"
	LogkeyProvider             = "provider"
	LogkeyRedisHost            = "redisHost"
	LogkeyTaxonID              = "taxonID"
	LogkeyDatastoreKey         = "datastoreKey"
	LogkeyTaxon                = "taxon"
	LogkeyPhoto                = "photo"
)
